# Generated by Django 5.1.2 on 2025-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
