# Generated by Django 5.1.2 on 2025-01-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='carrinho',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.DeleteModel(
            name='ItemCarrinho',
        ),
    ]
